### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by lm8** [flightcrank/pong#1]
Is there a license for this (such as GPL, BSD 2-clause, MIT, or some other standard OSI license)?  I know a couple of distributions that might be interested in adding a SDL based Pong game, but it would need to be under a license where they could distribute the source and executable.  Thanks.  

I've been looking at various SDL and ncurses based pong games and your version is very nice.

**Comment by flightcrank** [comment]
well mine is very simple. and probably needs a bit of a "tune up" if it
were to be used as an actual game for entertainment. it was merely an
exercise i used to learn SDL. its should probable be upgraded to SDL 2 as
well. your free to take it, use and modify it for any use you see fit.

joshua

**Comment by lm8** [comment]
Thanks.

I've been adding SDL2 compatibility to some of the other Open Source SDL (1.2.15) programs I like to use.  It should be fairly easy to add the option to use SDL2 instead of SDL to your code.  If you want patches to add SDL2 support, let me know.
