### ISSUE TITLE
Better AI

### ISSUE THREAD

**Issue by SeaPickle754** [flightcrank/pong#5]
[pong.c.zip](https://github.com/flightcrank/pong/files/5619509/pong.c.zip)

Hi, I have nothing wrong with this! This is so awesome and I need to do something like this one day. I just want to say, here is a version with a better ai. Thanks,
ILoveC++

**Comment by gagichce** [comment]
Make a PR!

**Comment by SeaPickle754** [comment]
Yeah, this was the first AI I ever learned how to do, and to this day, still is. I remember watching this in a video and thinking, "AI must be so easy!". Put laughs below.
