### ISSUE TITLE
how do i run the game?

### ISSUE THREAD

**Issue by Marvan0305** [flightcrank/pong#9]
How do i run the game on windows?

**Comment by flightcrank** [comment]
you just need a C compiler to compile the code to a executable. and SDL2 library to draw the graphics on the screen. Compilation instructions are in the readme file.

**Comment by Marvan0305** [comment]
Can you show how to play the game?

**Comment by flightcrank** [comment]
> Can you show how to play the game?

from memory your just use the arrow keys to move the paddle up or down. the other paddle is controlled by the computer.
